### ISSUE TITLE
Repository Server?

### ISSUE THREAD

**Issue by michaelfreitag** [SpringDataElasticsearchDevs/spring-data-elasticsearch#11]
Hi, I would like to try out. On which repository server do you publish?

**Comment by michaelfreitag** [comment]
git clone & mvn install are my friends.

**Comment by mohsinh** [comment]
Thanks for trying it !
Yes currently you need to build locally.
We are in touch with SpringSource and this will be soon available from Spring Repository :-)
let us know if you have any other doubt !
