### ISSUE TITLE
Pagination 1 based?

### ISSUE THREAD

**Issue by puug** [SpringDataElasticsearchDevs/spring-data-elasticsearch#15]
We're seeing odd behaviour with pagination where pages 0 & 1 are the same, and looking into it it's because in ElasticSearchTemplate, you subtract 1 from the page number, making it 1 based. Just wondering why this is in place as spring data pagination is page 0 based? See org.springframework.data.domain.PageImpl and you'll find this causes issues with the isFirst() flag.

**Comment by rizwanidrees** [comment]
You are right, It looks like it was introduced recently with f53c1bc66053c1ca830ab9ebfc6bebc2228864b6

**Comment by rizwanidrees** [comment]
I've reverted the change that introduced the bug, please pull the latest changes.

**Comment by mohsinh** [comment]
Ooops my bad, yes it was introduced in f53c1bc66053c1ca830ab9ebfc6bebc2228864b6.

Thanks Ryan for rectifying it !
