### ISSUE TITLE
Exception occurred in assertion

### ISSUE THREAD

**Issue by yl3w** [SpringDataElasticsearchDevs/spring-data-elasticsearch#22]
An mvn clean package on this repository includes an example that fails. it is infact amongst the first examples I tried and might be a user error.

The exception occurs in spring-data-elasticsearch, the results from ES itself are what I would expect.

https://github.com/maddalab/sample-es-application

**Comment by mohsinh** [comment]
Thanks you so much for rectifying it !

Agree documentation part of spring data elasticsearch is wrong for your test case. I will change that for sure.

It will return a single Object as internally it will call queryForObject of ElasticsearchTemplate class.
If you want multiple records please call for Page request.

Initially we implemented support for List<T> but it is not feasible as you could have 1000s of record and you don’t want to load all of them in a list at a time.
Hence List is replaced by Page request. And you can easily get List<T> by using getContent() method of Page.

I have added two test cases for detail information , you can always fork sample application project and add more test cases and play around !

[Test](https://github.com/BioMedCentralLtd/spring-data-elasticsearch-sample-application/blob/master/src/test/java/org/springframework/data/elasticsearch/repositories/SampleProductRepositoryTest.java)

I will talk to my team about repository methods that return List<T> with Pageable request. If it will be feasible then it will be available soon 

also you are using Client in your test case to delete data from index, which is not required as repository has deleteAll() default method to do that(see test case for more detail)

Hope that helps
Let me know if you still have doubt

**Comment by mohsinh** [comment]
Support for repository and template to have methods which will return List<T> is added...

please see below test cases for more information...

[Test](https://github.com/BioMedCentralLtd/spring-data-elasticsearch-sample-application/blob/master/src/test/java/org/springframework/data/elasticsearch/repositories/SampleProductRepositoryTest.java)
