### ISSUE TITLE
Define mapping

### ISSUE THREAD

**Issue by ghost** [SpringDataElasticsearchDevs/spring-data-elasticsearch#9]
If the index and type do not exist, spring-data-elasticsearch creates the index and adds a simple mapping for the given type. 

Is there a way to define the mapping we want to use for the type so that spring-data-elasticsearch will use it? Or must we configure our elasticsearch before?

**Comment by mohsinh** [comment]
Issue is already opened at [issue#5](https://github.com/BioMedCentralLtd/spring-data-elasticsearch/issues/5). We are working on it, It is going to be available soon. Please track on the issue 5 for this feature. Thanks

**Comment by ghost** [comment]
Ok. I didn't find that the issue https://github.com/BioMedCentralLtd/spring-data-elasticsearch/issues/5 was the same as this one. 
I mean the mapping is already created if it did not exist (simple mapping) so I don't quite understand the goal behind the other issue. 
Thanks for your response, I'll do the configuration of our index and types before using spring-data-elasticsearch.

**Comment by mohsinh** [comment]
Yes Spring Data Elasticsearch will automatically create mapping based on Field value given in your entity. however in issue#5 we will be giving support to create mapping from entity itself  with option to override defaults. It will look something like this

``` java
public class Book{
    @Id
    private String id;
    @Field(type="string",analyzer="keyword")
    private String keywords;

}
```

**Comment by ghost** [comment]
Thanks for the additional informations.

**Comment by michaelfreitag** [comment]
Hi,

I have integrated two features in my fork, you can grab it:
- DocumentId annotation to inject the ES document id where you want
- Set mapping on index creation driven by spring property descriptor (reflection)

https://github.com/mfreitag/spring-data-elasticsearch

Regards,
Michael

**Comment by mohsinh** [comment]
@mfreitag 
Thanks for the implementation, 
we wanted to have @Field annotation on the field name for dynamic mapping.

@Hanastaroth 
we have added support for this feature in cae34e50986ba3d1c58f7634da1e88202de409eb. Example is mentioned on https://github.com/BioMedCentralLtd/spring-data-elasticsearch/issues/5
